### ISSUE TITLE
duda.

### ISSUE THREAD

**Issue by itsfelipeh** [ocordova/gas-telegram-bot#1]
Hola ! me gusto mucho tu publicación de tu blog, y gracias a eso logre tener un bot operativo en Telegram, la duda es... que al integrarlo a un grupo e interactuar con el, las respuestas me llegan en una ventana privada y no en la sala grupal. podrías ayudarme ? 

Saludos

**Comment by ocordova** [comment]
¿Me podrías compartir tu código?

Cuando creas tu payload, debes mandar el mensaje al **chat.id**, no importa si es una persona o un grupo.

Ejemplo de un request desde un grupo:

```javascript
{
   "update_id":491865479,
   "message":{
      "message_id":913,
      "from":{
         "id":10610041,
         "is_bot":false,
         "first_name":"u00d3s (Human)",
         "username":"oscordova",
         "language_code":"es-MX"
      },
      "chat":{
         "id":-265498303,
         "title":"Test",
         "type":"group",
         "all_members_are_administrators":true
      },
      "date":1518561352,
      "text":"/quote",
      "entities":[
         {
            "offset":0,
            "length":6,
            "type":"bot_command"
         }
      ]
   }
}
```

**Comment by itsfelipeh** [comment]
//
Bot.prototype.replyToSender = function (text) {
  return this.request('sendMessage', {
    'chat_id': this.update.message.from.id,
    'text': text
  });
}

function CommandBus() {
  this.commands = [];
}

CommandBus.prototype.on = function (regexp, callback) {
  this.commands.push({'regexp': regexp, 'callback': callback});
}

CommandBus.prototype.condition = function (bot) {
  return bot.update.message.text.charAt(0) === '/';
}

CommandBus.prototype.handle = function (bot) {  
  for (var i in this.commands) {
    var cmd = this.commands[i];
    var tokens = cmd.regexp.exec(bot.update.message.text);
    if (tokens != null) {
      return cmd.callback.apply(bot, tokens.splice(1));
    }
  }
  return bot.replyToSender("ta malo el comando oee!! ");
}

**Comment by itsfelipeh** [comment]
espero que me puedas ayudar...

**Comment by ocordova** [comment]
Here you're replying to the sender of the message, not to the chat id.
```javascript
Bot.prototype.replyToSender = function (text) {
    return this.request('sendMessage', {
        'chat_id': this.update.message.from.id,
        'text': text
    });
}
```
Just change this line:
```
chat_id': this.update.message.from.id,
```
To this:
```
chat_id': this.update.message.chat.id,
```

**Comment by itsfelipeh** [comment]
funciono perfecto. gracias. !!!
